- packages/modul-components/src/components/autocomplete/autocomplete.html
Add the second argument (Index) to prevent duplicated keys in v-for directive
> bugfix/autocomplete_duplicated_keys => index des items

- packages/modul-components/src/components/breadcrumbs/__snapshots__/breadcrumbs.stories.ts.snap
- packages/modul-components/src/components/breadcrumbs/breadcrumbs.html
- packages/modul-components/src/components/breadcrumbs/breadcrumbs.stories.ts
- packages/modul-components/src/components/breadcrumbs/breadcrumbs.ts
- packages/modul-components/src/components/components-plugin.ts
Retirer le composant afficher plus du composant breadcrumbs et ajustement mineur aux dividers
https://jira.dti.ulaval.ca/browse/MODUL-1194
> MODUL-1194 - retirer afficher plus et ajuster dividers

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Tel que discuté, je propose une traduction des templates pour les PR / bug request / feature request en français afin d'en facilité l'écriture, j'ai aussi ajouté une section *Liens vers les récits / épopées* pour permettre le lien bi-directionel vers notre Jira interne.
> mise à jour des templates github

- packages/modul-components/src/components/popup/popup.ts
Correction du problème de la dropdown qui ouvre tout seul quand on choisi un élément de la liste déroulante
> Correction dropdown qui ouvre lors d'un choix dans la liste déroulante

- packages/modul-components/src/components/error-pages/error-conflict/__snapshots__/error-conflict.stories.ts.snap
- packages/modul-components/src/components/error-pages/error-conflict/error-conflict.lang.fr.json
Mise à jour des messages suite à la relecture d'Audrey.
- [ x] Storybook
> Ajustement des messages pour l'optimistic lock (Audrey)

- packages/modul-components/src/components/phonefield/phonefield.html
- packages/modul-components/src/components/phonefield/phonefield.scss
Fix largeur du MSelect de pays dans phonefield suite à beta.127
> Fix largeur et hauteur du phonefield

- packages/modul-components/src/components/dropdown/dropdown.ts
Sur un Dropdown filtrable, lorsque l'on écrit la valeur d'un des choix dans le input. Il n'est plus nécessaire de respecter la case ou les accents pour que le texte recherché devienne la sélection sur la fermeture de la liste.
https://jira.dti.ulaval.ca/browse/AEL-598
Lié mais pas directement à [MODUL-885](https://jira.dti.ulaval.ca/browse/MODUL-885)
> Dropdown: AEL-598 - Ignorer la case et accent du filtre sur close

- packages/modul-components/src/components/error-pages/error-session-expired/error-session-expired.html
- packages/modul-components/src/components/error-pages/error-session-expired/error-session-expired.ts
Pour permettre de spécifier l'adresse où redirigera le composant, ajout de la prop url.
Ajout de la prop target de façon préventive si on en a de besoin. Pourra être enlevé à la fin du dévelopement de R11-743 si non nécessaire.
En lancant mpo-shell, en accédant à la page d'expiration. Avec des information pour ces 2 props.
https://jira.dti.ulaval.ca/browse/MPOPO-841
> MErrorSessionExpired: Ajout de 2 props dans le composant

- packages/modul-components/src/components/accordion/accordion.scss
Fixe les problèmes de chevauchement de bordures (double bordure) dans les accordéons.
https://jira.dti.ulaval.ca/browse/ENA2-7874
> Ajustements à l'affichage des bordures

- packages/modul-components/src/components/multi-select/multi-select.ts
Le composant n'utilise plus des fonctions qui faisont des mutations direct sur le model.
> MMultiSelect: Éviter de faire des mutations directement sur le model

- packages/modul-components/src/components/pagination/pagination.html
- src/storybook/src/modul-components/components/pagination/__snapshots__/pagination.stories.ts.snap
Ajout de tooltips au icone precedant / suivant dans la maison
- [X ] Storybook
> Tooltips on back/forward

- packages/modul-components/src/components/table/__snapshots__/table.spec.ts.snap
- packages/modul-components/src/components/table/table.html
- packages/modul-components/src/components/table/table.scss
- src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
- src/storybook/src/modul-components/components/table/table.stories.ts
Correction des problèmes d'alignement dans le m-table lorsque les colonnes sont triables
[https://jira.dti.ulaval.ca/browse/ENA2-8200](https://jira.dti.ulaval.ca/browse/ENA2-8200)
> Correctifs d'alignement du m-table

- packages/modul-components/src/components/datefields/datefields.spec.ts
- packages/modul-components/src/components/datefields/datefields.ts
- packages/modul-components/src/components/error-message/error-message.spec.ts
- packages/modul-components/src/components/error-message/error-message.ts
- packages/modul-components/src/components/error-pages/error-technical-difficulty/error-technical-difficulty.spec.ts
- packages/modul-components/src/components/error-pages/error-technical-difficulty/error-technical-difficulty.ts
- packages/modul-components/src/components/message-page/message-page.sandbox.ts
- packages/modul-components/src/filters/date/date.ts
- packages/modul-components/src/filters/date/time/time.ts
- src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
- tslint.json
En vue du retrait éventuel et souhaitable de moment.js, la première étape est au moins d'éviter d'ajouter de nouvelles références à moments.js. Voir aussi https://github.com/you-dont-need/You-Dont-Need-Momentjs
Ne s'applique pas.
https://jira.dti.ulaval.ca/browse/ENA2-8286
> Ban moment

- packages/modul-components/src/components/searchfield/searchfield.scss
**Problème**
Dans safari le m-searchfield affiche la bordure en double.
**Bugfix**
m-searchfield : Retirer les styles par défaut du input de type "search" dans le navigateur safari
> Retirer les styles par default de safari

- packages/modul-components/src/components/tooltip/tooltip.html
- packages/modul-components/src/components/tooltip/tooltip.ts
- src/storybook/src/modul-components/components/tooltip/__snapshots__/tooltip.stories.ts.snap
- src/storybook/src/modul-components/components/tooltip/tooltip.stories.ts
En mode Icon (Default) il est possible de changer l'icône par défaut avec une nouvelle prop
Tooltip: Nouvelle prop iconName pour changer l'icône par défaut en mode Icon
> Tooltip: Ajout d'une prop pour pouvoir changer l'icône

- .circleci/config.yml
- package.json
Publication des branches vers docker.io
> feature/ deploy docker image from circle-ci

- packages/modul-components/src/components/icon/icon.ts
Corrige le bug qui faisait en sorte que le service de sprites ne retournait pas le path du external sprite si ce dernier commençait par m-svg__ 
https://jira.dti.ulaval.ca/browse/ENA2-8224
> Retourner un icône m-svg__*

- packages/modul-components/src/components/accordion-group/accordion-group.html
- packages/modul-components/src/components/accordion-group/accordion-group.ts
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/accordion-group-disabled.stories.ts
- src/storybook/src/modul-components/components/accordion-group/accordion-group-enabled.stories.ts
- src/storybook/src/modul-components/components/accordion-group/accordion-group-open-all.stories.ts
- src/storybook/src/modul-components/components/accordion-group/accordion-group-opened-ids.stories.ts
- src/storybook/src/modul-components/components/accordion-group/accordion-group-secondary-content.stories.ts
- src/storybook/src/modul-components/components/accordion-group/accordion-group.stories.ts
- src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
- src/storybook/src/modul-components/components/accordion/accordion.stories.ts
La réactivité de l'accordion-group en présence de ouvrir tous / fermer tous n'était pas complète.  Dans le cas où un accordion-group contient un accordion avec du contenu qui n'est pas immédiatement chargé, l'open all / close all ne s'affiche pas jusqu'à temps que l'on intéragisse avec un des accordions du groupe une première fois.
path storybook pour reproduire le cas:
?path=/story/modul-components-m-accordion-group-openall-true--with-delayed-accordion-content
Un accordéon désactivé à l'intérieur d'un groupe d'accordéons ne répond plus aux commandes Tout ouvrir / Tout fermer. Il conserve son état en tout temps.
https://jira.dti.ulaval.ca/browse/ENA2-8000
> Fix accordeon open all reactivity

- packages/modul-components/src/components/popper/popper.html
il semble avoir sur develop par un changement de la PR #101 au niveau du dropdown
http://develop-ul-modul-dv01.pca.svc.ulaval.ca/storybook/index.html?path=/story/modul-components-m-dropdown--default
J'ai effectué ce changement et le problème semble règlé je suis pas certain de bien comprendre pourquoi.. peut-etre que @jfdion peut m'éclairer ❓
> fix dropdown selection problem

- src/storybook/package.json
Ceci causait que le package storybook était taggué a chaque release de modul-component ce qui est redondant lors des petits bugfix
> misc: remove modul components dev dependencie in storybook

- packages/modul-components/src/components/table/table.html
- src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
- src/storybook/src/modul-components/components/table/table.stories.ts
Ajout de la classe personnalisée de l'objet de la colonne sur les td du tableau.
L'attribut class de l'objet MColumnTable est appliqué sur les th et td maintenant, spécifier dans votre CSS que vous voulez seulement appliquer du style sur les th 
`th.classePersonnalisee {
padding: 0 $m-spacing--xs 0 0;
}`
https://jira.dti.ulaval.ca/browse/ENA2-8279
> Ajout class sur les td

- packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html
- packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
- packages/modul-components/src/components/rich-text-editor/rich-text-editor.html
- packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
- src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.html
La PR consiste à ajouter un paramètre permettant de gérer la hauteur minimale de l'éditeur de texte riche.
Pas de breaking change
https://jira.dti.ulaval.ca/browse/AEL-1468
> add parameter for default rich-text-editor size

- packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.scss
Il manquait un espace entre le /deep/ et le sélecteur (ligne 47). Ce sélecteur était aussi défini 2 fois, j'en ai profité pour les fusionner.
J'ai retiré une ligne en trop dans l'entête.
Tester dans le projet Admission et Brio
https://jira.dti.ulaval.ca/browse/AEL-1639
https://jira.dti.ulaval.ca/browse/ENA2-8120
> RichTextEditor: Ajustement visuel

- packages/modul-components/package.json
- packages/modul-components/src/components/phonefield/phonefield.html
- packages/modul-components/src/components/phonefield/phonefield.scss
- packages/modul-components/src/components/select/base-select/base-select.html
- packages/modul-components/src/components/select/base-select/base-select.scss
- packages/modul-components/src/components/select/base-select/base-select.ts
- packages/modul-components/src/components/select/select.html
- packages/modul-components/src/components/select/select.ts
- src/storybook/conf/storybook/config.ts
- src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
- src/storybook/src/modul-components/components/select/select.stories.ts
- yarn.lock
Les grosse liste cause des probleme de performance sur les appareil mobile de basse performance (voir ticket ci-dessous). Nottament au niveau du m-phonefield ou on doit afficher plus de 250 pays avec leur drapeau
J'ai introduit un virtual-scroll dans le m-select qui permet d'ameliorer les performance pour les grosse liste 
ajout d'une story virtual scroll dans le m-select et voir stories du m-phonefield
https://jira.dti.ulaval.ca/browse/AEL-1517
> Feature/ael 1517 - implementation virtual-scroll dans le m-select

- src/modul-website/public/content/standards/accessibility-standards/accessibility-standards.why.fr.md
- src/modul-website/public/content/standards/editorial-standards/editorial-standards.formats.fr.md
- src/modul-website/public/content/standards/editorial-standards/editorial-standards.message-bank.fr.md
- src/modul-website/public/content/standards/editorial-standards/editorial-standards.punctuation.fr.md
- src/modul-website/public/content/standards/editorial-standards/editorial-standards.tone.fr.md
- src/modul-website/public/content/standards/visual-standards/visual-standards.breakpoints.fr.md
- src/modul-website/public/content/standards/visual-standards/visual-standards.colors.fr.md
- src/modul-website/public/content/standards/visual-standards/visual-standards.iconography.fr.md
- src/modul-website/public/content/standards/visual-standards/visual-standards.typography-styles.fr.md
- src/modul-website/public/content/standards/visual-standards/visual-standars-iconography/visual-standars-iconography-documentations.fr.md
- src/modul-website/src/components/demo/demo.html
- src/modul-website/src/components/demo/demo.scss
- src/modul-website/src/components/expendable-panel/expandable-panel.html
- src/modul-website/src/components/expendable-panel/expandable-panel.scss
- src/modul-website/src/components/icon-gallery/icon-gallery.scss
- src/modul-website/src/components/logo/logo.scss
- src/modul-website/src/components/markdown/markdown.scss
- src/modul-website/src/pages/components/component/component-details.html
- src/modul-website/src/pages/components/component/component-details.scss
- src/modul-website/src/pages/components/components.html
- src/modul-website/src/pages/components/components.scss
- src/modul-website/src/pages/components/components.ts
- src/modul-website/src/pages/home/home.scss
Voici les modifications qui ont été effectué à modul-website:
* Ajouter les effets *:hover* et *:focus* sur les boutons précédent et suivant des pages de composant
* Ajuster la couleur et le niveau sémantique des titres du composant *component-details*
* Réduire la taille du logo *Modul* en version mobile dans la page d’accueil
* Aligner les icône de mode d’affichage dans la page *iconographie/icons* (https://ulaval.github.io/modul/Normes/graphique/iconographie/icons)
* Ajuster le padding du corps du composant *expandable-panel*
* **Modifier le balisage des markdown des page norme**
* Mettre les titres (h1 à h6) en minuscule dans les fichier.md
* Ajouter un h1 à chaque page de norme
Tester les modifications avec la commande 
`yarn run website`
> Ameliorer styles de modul-website

- packages/modul-components/src/mixins/portal/portal.ts
Check if the v-m-popup element is enabled before opening portal.
Close #131
> MDropdown - Mobile - Disabled

- packages/modul-components/src/components/pagination/pagination.lang.en.json
- packages/modul-components/src/components/pagination/pagination.lang.fr.json
- packages/modul-components/src/components/pagination/pagination.ts
- src/storybook/src/modul-components/components/pagination/__snapshots__/pagination.stories.ts.snap
- src/storybook/src/modul-components/components/pagination/pagination.stories.ts
Changement visuel de la pagination. Voir https://jira.dti.ulaval.ca/browse/ENA2-8141
- [X ] Amélioration (ajout par example une nouvelle propriété, évènement, slot ou méthode à un composant existant sans `breaking change`)
- [X ] Storybook
> Status text: display items number instead of pages

- packages/modul-components/src/components/accordion/accordion.scss
**Problème**
Lorsque le composant `m-accodion` n'est pas le premier enfant de son parent, la propriété `border-top` ne s'affiche pas.
**Modification**
Ajouter la propriété `border-top` en tout temps sur le ` m-accodion` seulement s'il n'est pas suive de son frère.
> Supprimer le border-top sur le projet accodéon

- packages/modul-components/src/components/popper/popper.ts
Bug propre à brio
Ajouter la possibilité de choisir un container custom pour popper.
https://jira.dti.ulaval.ca/browse/ENA2-8598
> Ajouter la possibilité de choisir à la main le container pour popper

- packages/modul-components/src/components/dropdown/dropdown-item/dropdown-item.scss
- src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
- src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts
Changer la couleur des items disabled de la dropdown
https://jira.dti.ulaval.ca/browse/AEL-1644
> change dropdown item disabled color

- packages/modul-components/src/components/datepicker/datepicker.html
- packages/modul-components/src/components/datepicker/datepicker.ts
On mobile, both keyboard and the popup are displayed at the same time, in order to hide the keyboard I've turned off the inputmask focus on mobile(less than tablet)
> Disable datepicker input-mask focus on mobile

- .vscode/launch.json
- .vscode/settings.json
- jest.config.js
- src/storybook/jest.config.js
J'ai corrigé le problème d'exécution des test jest a partir du plugin pour le projet modul-component!
> fix vscode jest extension in repo

- packages/modul-components/src/components/option/option-item/option-item.scss
- packages/modul-components/src/components/option/option.html
- packages/modul-components/src/components/option/option.ts
- src/storybook/src/modul-components/components/option/__snapshots__/option.stories.ts.snap
- src/storybook/src/modul-components/components/option/option.stories.ts
J'ai simplement ajouté la possibilité d'ajouter une largeur custom pour les options de menu.
À l'origine, si je me souviens bien, on avait fixé la largeur parce que le plugin avait de la difficulté à bien se positionner. Le tout semble bien fonctionner maintenant.
https://jira.dti.ulaval.ca/browse/ENA2-7253
> Add max-width prop for m-option

- packages/modul-components/src/components/toast/toast.html
- packages/modul-components/src/components/toast/toast.ts
- packages/modul-components/src/utils/toast/toast-service.ts
- src/storybook/src/modul-components/components/toast/__snapshots__/toast.stories.ts.snap
- src/storybook/src/modul-components/components/toast/toast.stories.ts
Show/Hide the MToast close button
> MToast optional close button

- packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
Apres plusieurs test dans admission , on va rollback cette PR pour une nouvelle solution
Reverts ulaval/modul#154
> Revert "Bugfix/navbar item resizing optimization"

- packages/modul-components/src/components/photo-editor/crop-image/crop-image.ts
Edge ne supporte pas le constructeur de File
https://caniuse.com/#feat=fileapi
En utilisant EDGE, on ne devrait plus avoir d'erreur dans la console lors du click sur "enregistrer"
http://feature-ena2-8960-image-edge-ul-modul-dv01.pca.svc.ulaval.ca/storybook/index.html?path=/story/modul-components-m-photo-editor--default-story
https://jira.dti.ulaval.ca/browse/ENA2-8960
> [m-photo-editor] Correction création image sur edge

- packages/modul-components/src/components/timepicker/timepicker.html
- packages/modul-components/src/components/timepicker/timepicker.sandbox.html
- src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
- src/storybook/src/modul-components/components/timepicker/__snapshots__/timepicker.stories.ts.snap
- src/storybook/src/modul-components/components/timepicker/timepicker.stories.ts
Ajout d'une prop sur la composante `timepicker` pour permettre de marquer un champ required
Added support for prop `required-marker` on timepicker component
[ENA2-8799](https://jira.dti.ulaval.ca/browse/ENA2-8799?focusedCommentId=1409177&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1409177)
> [m-timepicker] added support for required maker for timepicker

- CONTRIBUTING.md
> [doc] modification contributing guide

- packages/modul-components/src/components/phonefield/assets/all-countries-en.ts
- packages/modul-components/src/components/phonefield/assets/all-countries-fr.ts
Correcting the International dial code (prefix) for some north american countries with 4 digits, Example for Anguilla instead of using +1-264 it will be +1
For more details: https://fr.wikipedia.org/wiki/Plan_de_num%C3%A9rotation_nord-am%C3%A9ricain
> bugfix/phonenumber-prefixes => phonefield prefixes correction

- packages/modul-components/src/components/expandable-layout/expandable-layout.scss
- src/storybook/src/modul-components/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap
- src/storybook/src/modul-components/components/expandable-layout/expandable-layout.stories.ts
> [m-expandable-layout] Ajouter z-index sur le panneau en mode overContent

- packages/modul-components/src/filters/date/time/time.ts
TS2440: Import declaration conflicts with local declaration of 'TimeFilterOptions'.
Pour être capable de compiler en TypeScript 3.7. Voir https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/ section Local and Imported Type Declarations Now Conflict
> [f-m-time] Pour régler une erreur TypeScript 3.7

- packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.html
- packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.ts
Rends disponible la fonctionnalité d'afficher des erreurs dans le address-lookup-field.
https://jira.dti.ulaval.ca/browse/ENA2-6702
> [m-address] MODUL-1209 - Add error message on address-lookup-field

- src/modul-website/public/content/standards/editorial-standards/editorial-standards.formats.fr.md
Ajout d'une section dans la page Normes éditoriales > Formats pour les règles d'affichage d'une somme d'argent.
- [ x ] Documentation/storybook (changement à la documentation ou aux storybooks qui n'affecte aucun package)
- [ x ] website
http://feature-doc-filter-money-ul-modul-dv01.pca.svc.ulaval.ca/website/index.html#/Normes/editorial/format
Documentation de `Normes éditoriales > Formats` : Ajout des règles d'affichage d'une somme d'argent.
> [doc] Feature/doc filter money

- packages/modul-components/src/components/steppers/steppers-item/steppers-item.html
- packages/modul-components/src/components/steppers/steppers-item/steppers-item.scss
- src/storybook/src/modul-components/components/steppers/__snapshots__/steppers.stories.ts.snap
- src/storybook/src/modul-components/components/steppers/steppers.stories.ts
Ajouter 1 px de padding autour de l'icon dans le m-stepper-item puisque l’icône est parfois collé sur la bordure si l’icône est carré.
Avant : 
Après : 
Breaking change visuel
https://jira.dti.ulaval.ca/browse/ENA2-9143
> [m-steppers] Ajouter du padding autour de l'icon dans le m-stepper-item

- packages/modul-components/src/mixins/portal/portal.ts
- packages/modul-components/src/utils/modul/modul.ts
> merge develop into master Develop

- packages/modul-components/src/utils/address-lookup/address-lookup-loqate-service.spec.ts
- packages/modul-components/src/utils/address-lookup/address-lookup-response-mapper.ts
- packages/modul-components/src/utils/address-lookup/address.ts
Le type address contient maintenant un ID correspondant au place_id pour google et au ID pour loqate
https://jira.dti.ulaval.ca/browse/ENA2-9589
> Ajouter le id dans address-lookup

- packages/modul-components/src/components/popup/popup.html
- packages/modul-components/src/components/popup/popup.ts
- packages/modul-components/src/mixins/portal/portal.ts
Voici une autre solution pour régler le probleme de resising des popup de la PR #207 . La solution est dans m-popup donc en theorie seul les composant l'utilisant sont affectés
m-dropdown
m-select
m-datepicker
m-timepicker
m-tooltip
> [m-popup] Correctif probleme de resizing pour le popup

- packages/modul-components/src/utils/modul-date/modul-date.ts
Changement de la fonction toString() de pour corriger le fonctionnement du date picker dans une timezone différente. toString() utilise toISOString() qui transforme la date sélectionnée en UTC.
En ce moment, quand on sélectionne une date en étant dans une autre timezone, la date sélectionnée est convertie en UTC. Donc, si on sélectionne le 3 janvier 8AM GMT+12, on obtient le 2 janvier puisque toISOStrin() retire l'offset.
_Ce changement règle aussi 30+ tests unitaires qui échouent lorsqu'on teste avec une autre timezone. Aucun test supplémentaire n'a été ajouté puisque je n'ai pas trouvé d'option pour changer le timezone de jest pour une suite de tests. Ça me semble uniquement possible en global._
> ModulDate toString uses yyyy-mm-dd format

- packages/modul-components/src/components/rich-text-editor/rte-internal.scss
Overrider le z-index de Froala en mode pleine page, afin de correspondre à notre valeur par défaut dans le fichier utils\modul\modul.ts
> Rich Text Editor- en mode pleine page, l'insertion d'image ne fonctionne pas

- packages/modul-components/package.json
- yarn.lock
Figer la version de froala-editor pour éviter de bumper la version automatiquement en faisant un npm install dans un autre projet.
Faire un yarn pack local et tester ensuite dans un projet qui utilise modUL.
> [m-rich-text-editor] Figer la version de froala-editor pour éviter les mises à jour surprises

- packages/modul-components/src/components/popup/popup.html
- packages/modul-components/src/components/popup/popup.ts
- packages/modul-components/src/mixins/portal/portal.ts
- packages/modul-components/src/utils/modul/modul.ts
Pour fixer les bugs introduits dans la PR #145
> [m-portal] Émettre à nouveau un événement update: et gérer les stackIndex à 0

- packages/modul-components/src/components/rich-text-editor/rte-internal.scss
> Revert "[m-richtext-editor] Rich Text Editor- en mode pleine page, l'insertion d'image ne fonctionne pas"

- packages/modul-components/src/components/multi-select/multi-select.html
- packages/modul-components/src/components/multi-select/multi-select.ts
- src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
- src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap
- src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
Ajout de la fonctionnalité Placeholder sur le MMultiSelect
> MMultiSelect : Ajout du Placehoder dans le multi-select

- packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html
- packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
- packages/modul-components/src/components/rich-text-editor/rich-text-editor.html
- packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
- src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.html
- src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.ts
Ajouter une fonction permettant de passer une fonction de validation custom au text rich editor pour faire la validation des images téléversées sur des critères autres que ceux de base, et afficher un message personnalisé.
> ENA2-9651 - ajouter fonction custom pour valider image rich text

- packages/modul-components/src/components/searchfield/searchfield.ts
- src/storybook/src/modul-components/components/searchfield/__snapshots__/searchfield.stories.ts.snap
- src/storybook/src/modul-components/components/searchfield/searchfield.stories.ts
Il n'y avait pas d'événement sur le clique du "X" alors je l'ai ajouté
[https://jira.dti.ulaval.ca/browse/ENA2-9062](https://jira.dti.ulaval.ca/browse/ENA2-9062)
> [m-searchfield] Ajout événement emptyField sur le searchfield

- CODEOWNERS
Pour que tu sois inclus automatiquement dans les review du rich-text-editor
> [misc] Ajout de cabob comme code-owner pour le m-rich-text-editor

- packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Il faut permettre le style « text-decoration » dans le copie/colle.
> [m-rich-text-editor] ENA2-8914 - RTE : les options alignement, souligné et barré sont perdues lors du copier/coller

- packages/modul-components/src/components/tooltip/tooltip.scss
- packages/modul-components/src/components/tooltip/tooltip.ts
Permet de personnalisé le max-height du tooltips.
> [m-tooltip] add customisable max-height

- packages/modul-components/src/components/component-names.ts
- packages/modul-components/src/components/input-mask/input-mask.ts
- packages/modul-components/src/components/maskedfield/maskedfield.html
- packages/modul-components/src/components/maskedfield/maskedfield.scss
- packages/modul-components/src/components/maskedfield/maskedfield.ts
- src/storybook/src/modul-components/components/maskedfield/__snapshots__/maskedfield.stories.ts.snap
- src/storybook/src/modul-components/components/maskedfield/maskedfield.stories.ts
- src/storybook/src/modul.ts
Création du composant générique qui permet d'utiliser m-input-mask dans un composant
Billet JIRA : https://jira.dti.ulaval.ca/browse/ENA2-10271
Branche déployé : http://feature-ena2-10271-creer-composant-m-maskefield-ul-modul-dv01.pca.svc.ulaval.ca/storybook/index.html?path=/story/modul-components-m-maskedfield--default-story
> [m-maskedfield] - Création du composant pour faire des masques d'input

- packages/modul-components/src/assets/icons/sprites-default.svg
- src/storybook/src/modul-components/components/icon/icon.stories.ts
Ajout de l'icon **m-svg__lock** au sprite svg.
http://localhost:8082/?path=/story/modul-components-m-icon--name-short
> Ajouter l'icone lock au sprite svg

- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.ts
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.ts
- tslint.json
> [m-organize-table-columns] Bugfix/Probleme de import dans le MOrganizeTableColumns

- packages/modul-components/src/components/modal/modal.scss
- packages/modul-components/src/components/modal/modal.ts
Correction de bug lié à ce PR https://github.com/ulaval/modul/pull/251
**Correction 1**
**Correction 2**
> m-modal et m-dialog: améliorer réactivité des slots

- packages/modul-components/src/components/modal/modal.scss
- packages/modul-components/src/components/modal/modal.ts
**Modification dans le `m-modal`**
Changer condition d'affichage du message d'erreur dans le mounted
> m-modal: Changer condition d'affichage du message d'erreur dans le mounted

- packages/modul-components/src/components/expandable-layout/expandable-layout.scss
The addition of overContent prop changed the original behaviour. When overContent prop is set to false, there is now a scrollbar in the side panel instead of having the panel to take all the space needed for its content. This fix reverts to the original behaviour when overContent  is set to false.
https://jira.dti.ulaval.ca/browse/ENA2-9776
> [m-expandable-layout] Remove unwanted scroll when overContent is false

- packages/modul-components/src/components/phonefield/phonefield.ts
- packages/modul-components/src/lang/en.ts
- packages/modul-components/src/lang/fr.ts
- packages/modul-components/src/lib.ts
- packages/modul-components/src/utils/component/component-mixin.ts
- packages/modul-components/src/utils/utils-plugin.ts
Introduction d'une mixin global dans modul qui permet de configurer les composants d'un projet MODUL de facon individuel afin de permettre un meilleur treeshaking des composants. Cette configuration sera utilisé initialement par les fichiers i18n et par la suite bonifié avec l'ajout des icons du composant (voir #225)
Example d'utilisation 
```
@WithRender
@Component({
modul: {
i18n: {
'fr': require('./phonefield.lang.fr.json'),
'en': require('./phonefield.lang.en.json')
}
},
mixins: [
InputState,
InputWidth,
InputLabel,
InputManagement
],
components: {
MInputMask,
MSelectVirtualScroll,
MSelectItem
}
})
export class MPhonefield extends ModulVue {
``` 
J'ai modifié le m-phonefield pour tester l'utilisation 
https://jira.dti.ulaval.ca/browse/MPOPO-1017
> Mixin global pour la configuration individuelle des composantes MODUL

- packages/modul-components/src/components/expandable-layout/expandable-layout.scss
Force le panneau à prendre 100% de la hauteur de la zone du m-expandable-layout lorsqu'en mode normal (pas over-content).
Testé dans différents cas dans Brio et sur le site web de modul.
> [m-expandable-layout] Set height 100% on panel content

- packages/modul-components/src/components/overlay/overlay.html
- packages/modul-components/src/components/overlay/overlay.ts
- src/storybook/src/modul-components/components/overlay/__snapshots__/overlay.stories.ts.snap
- src/storybook/src/modul-components/components/overlay/overlay.stories.ts
Aucun impact sur le composant, ajout d'un props avec une valeur par défaut qui ne modifie pas le comportement du composant
https://jira.dti.ulaval.ca/browse/ENA2-10468
> [m-overlay] Ajout d'une props pour enlever le footer

- yarn.lock
fix pour le security issues https://github.com/ulaval/modul/network/alert/yarn.lock/minimist/open
procedure manuel de changement du yarn.lock tel que décrit dans https://stackoverflow.com/questions/55131928/yarn-upgrade-to-fix-yarn-audit-errors
> fix security issues

- packages/modul-components/src/filters/date/date.ts
- packages/modul-components/src/filters/date/time-elapsed/time-elapsed.lang.en.json
- packages/modul-components/src/filters/date/time-elapsed/time-elapsed.lang.fr.json
- packages/modul-components/src/filters/date/time-elapsed/time-elapsed.ts
- packages/modul-components/src/filters/filter-names.ts
- packages/modul-components/src/lang/en.ts
- packages/modul-components/src/lang/fr.ts
- src/storybook/src/modul-components/filters/date/time-elapsed/__snapshots__/time-elapsed.stories.ts.snap
- src/storybook/src/modul-components/filters/date/time-elapsed/time-elapsed.stories.ts
- src/storybook/tests/polyfills.js
Ajouter un filtre de date qui retourne le temps écoulé selon les normes de la section temps écoulé ici : https://ulaval.github.io/modul/Normes/editorial/format
JIRA : https://jira.dti.ulaval.ca/browse/ENA2-10529
ENVIRONNEMENT :
> [f-m-time-elapsed] - Création du filtre temps écoulés

- packages/modul-components/src/utils/i18n/i18n.spec.lang.fr.json
- packages/modul-components/src/utils/i18n/i18n.spec.ts
- packages/modul-components/src/utils/i18n/i18n.ts
Ajout du support pour le modificateur `0` dans les chaines de traduction
``` 
"medaille-olympique.0": "Aucun médaillé olympique",
"medaille-olympique.0.f": "Aucune médaillée olympique",
```
$i18n: Added support for `0` as a number modifier in translation keys
https://jira.dti.ulaval.ca/browse/ENA2-10362
> [$i18n] Added support for the 0 quantifier for translation keys

- packages/modul-components/src/components/popup/popup.html
- packages/modul-components/src/filters/filter-names.ts
- packages/modul-components/src/filters/phone/phone.ts
- src/storybook/src/modul-components/filters/date/time-elapsed/__snapshots__/time-elapsed.stories.ts.snap
- src/storybook/src/modul-components/filters/date/time-elapsed/time-elapsed.stories.ts
- src/storybook/src/modul-components/filters/phone/__snapshots__/phone.stories.ts.snap
- src/storybook/src/modul-components/filters/phone/phone.stories.ts
Ajout d'un filtre pour formater les # de téléphone en format national ou international
- [x ] Nouvelle fonctionalité (nouveau composant, directive, filtre ou service)
- [x ] Storybook
Aucun
https://jira.dti.ulaval.ca/browse/ENA2-9916
> [f-m-phone] Ajout d'un filtre pour les no de téléphone

- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.html
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.scss
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.ts
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.html
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.lang.en.json
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.lang.fr.json
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.scss
- packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.ts
- src/storybook/src/modul-components/components/organize-table-columns-modal/__snapshots__/organize-table-columns-modal.stories.ts.snap
- src/storybook/src/modul-components/components/organize-table-columns/__snapshots__/organize-table-columns.stories.ts.snap
QA visuel des composants `m-organize-table-columns` et `m-organize-table-columns-modal`.
**Liste des ajustements**
* Modifier le padding des éléments HTML du composant `m-organize-table-columns`
* Nettoyage dans le balisage des composants (supprimer les div inutiles)
* Préfixer le nom des classes CSS par `m-`
* Remplacer l'icone de **+** par le composant modul `m-add`
* Ajouter des espaces insécable (_NBSP_) dans les fichier de langue des composants.
@chuckmah, le `%(_NBSP_)s` semble ne pas fonctionner. Pourrais-tu vérifier pourquoi ça ne fonctionne pas?
> m-organize-table-columns: QA visuel

- packages/modul-components/src/components/datepicker/datepicker.ts
- packages/modul-components/src/utils/modul-date/modul-date.spec.ts
- packages/modul-components/src/utils/modul-date/modul-date.ts
**Bonification de la méthode `subtract()` du `ModulDate`**
- Possibilité d'ajouter ou soustraire des jours ou des mois d'une date.
- Mise à jour des test unitaire des méthodes `subtract()` et `add()` du `ModulDate`
La méthode est testée dans les tests unitaires.
> ModulDate: Addition et soustraction des dates par mois ou par jour

- packages/modul-components/src/components/radio-group/radio-group.html
- packages/modul-components/src/components/radio-group/radio-group.ts
- src/storybook/src/modul-components/components/radio-group/__snapshots__/radio-group.stories.ts.snap
- src/storybook/src/modul-components/components/radio-group/radio-group.stories.ts
Ajout de la props validationMessagePosition pour pouvoir positionner les messages d'erreurs dessous les radios.
[https://jira.dti.ulaval.ca/browse/ENA2-10597](https://jira.dti.ulaval.ca/browse/ENA2-10597)
> [m-radio-group] Ajout de la props validationMessagePosition

- packages/modul-components/src/components/phonefield/phonefield.html
- packages/modul-components/src/components/phonefield/phonefield.ts
Fix du problème de modèle qu'il n'est pas émit de la même façon par le virtual-scroll dans ModUL VS Brio
https://jira.dti.ulaval.ca/browse/ENA2-10664
> [m-phonefield] - Fix du model non cohérent dans Brio VS Modul

- packages/modul-components/src/utils/form/form-group.spec.ts
- packages/modul-components/src/utils/form/form-group.ts
Ajout des méthodes containsControl et setControl. Enlever l'erreur qui est envoyé sur le removeControl.
**containsControl** -> Retourne si le contrôleur existe ou non.
**setControl** -> Efface le contrôleur s'il existe et ensuite l'ajoute.
[https://jira.dti.ulaval.ca/browse/ENA2-10516](https://jira.dti.ulaval.ca/browse/ENA2-10516)
> [m-form] Ajout de méthodes dans le form-group et modification de removeControl

- packages/modul-components/src/components/transitions/slide-transition/slide-transition.ts
- src/storybook/src/modul-components/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
- src/storybook/src/modul-components/components/transitions/slide-transition/slide-transition.stories.ts
**Problème**
Lorsqu'on utilise le composant m-slider-transition, la page scroll toujours vers l'offset 0 du composant pendant qu'une transition est effectuée. J'ai donc ajouté la prop `automatic-scroll:boolean` pour arrêter le scroll lorsqu'on le désire.
Lien vers la story: http://localhost:8082/?path=/story/modul-components-m-slide-transition--automatic-scroll-false
Pour tester l'arrêt du scroll, simplement rétrécir la hauteur de son navigateur 400px.
http://localhost:8082/?path=/story/modul-components-m-slide-transition--automatic-scroll-false
> [m-slide-transition] ajouter la prop 'automatic-scroll' pour arrêter le scroll automatique

- packages/modul-components/src/components/input-mask/input-mask.html
- packages/modul-components/src/components/input-mask/input-mask.ts
- packages/modul-components/src/components/phonefield/formatter/custom-asyoutype.ts
- packages/modul-components/src/components/phonefield/phonefield.html
- packages/modul-components/src/components/phonefield/phonefield.scss
- packages/modul-components/src/components/phonefield/phonefield.ts
- src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
- src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
suite a une suggestion de @jipigi  J'ai enlevé la dependance vers cleave-phone.i18n.js  pour le remplacer vers une implementation qui utilise libphonenumber-js qui est beaucoup plus lightweight. 
il faudra tester que le masque est correct.
http://feature-replace-cleave-phone-i18n-js-ul-modul-dv01.pca.svc.ulaval.ca/storybook/index.html?path=/story/modul-components-m-phonefield--default-story
https://jira.dti.ulaval.ca/browse/ENA2-10635
> [m-phonefield] Remove cleave-phone.i18n.js 

- packages/modul-components/src/components/integerfield/integerfield.html
- src/storybook/src/modul-components/components/integerfield/__snapshots__/integerfield.stories.ts.snap
- src/storybook/src/modul-components/components/integerfield/integerfield.stories.ts
Permettre l'autocomplete au champ m-integerfield pour pouvoir faire de autofill avec les navigateurs
https://jira.dti.ulaval.ca/browse/ENA2-10680
> [m-integerfield] - Ajout autocomplete au m-integerfield + stories

- packages/modul-components/src/components/form/form.lang.en.json
- packages/modul-components/src/components/form/form.lang.fr.json
- packages/modul-components/src/utils/form/validators/phone/phone.spec.ts
- packages/modul-components/src/utils/form/validators/phone/phone.ts
- packages/modul-components/src/utils/form/validators/validator-error-keys.ts
- src/storybook/src/modul-components/components/form/__snapshots__/form.validators.stories.ts.snap
- src/storybook/src/modul-components/components/form/form.validators.stories.ts
Ajouter le PhoneValidator comme autre type de validation dans le m-form
https://jira.dti.ulaval.ca/browse/ENA2-10690
> [ControlValidator] - Ajouter le PhoneValidator pour la validation dans le m-form

- packages/modul-components/src/components/modal/modal.html
- packages/modul-components/src/components/modal/modal.scss
- packages/modul-components/src/components/modal/modal.ts
- src/storybook/src/modul-components/components/modal/__snapshots__/modal.stories.ts.snap
- src/storybook/src/modul-components/components/modal/modal-stories.scss
- src/storybook/src/modul-components/components/modal/modal.stories.ts
Comme j'avais fait pour le input-style, j'ai réfactoré légèrement les styles de la modal pour permettre : 
- la personnalisation des paddings, permet de supprimer toute les props poches de paddings
- de contrôler le offset top de la fenêtre en mobile, pour ajuster l'ouverture s'il y a du contenu fixe par exemple.
https://jira.dti.ulaval.ca/browse/ENA2-10753
> [m-modal]Refactor modal (ajout variable css)

- packages/modul-components/src/components/phonefield/assets/all-countries-en.ts
- packages/modul-components/src/components/phonefield/assets/all-countries-fr.ts
La liste déroulante qui permet de choisir le pays dans le phonefield affiche entre parenthèses la traduction du pays dans sa langue. Ça peut être utile pour une application complètement localisée mais dans nos applications, le francais ou l'anglais sont des prérequis. Donc connaitre le nom de son pays dans une de ces deux langues ne devrait pas poser de problème.
Aussi, dans une interface destinée aux gestionnaires, afficher les traduction ne fait aucun sens puisque le gestionnaire a comme langue maternelle soit le français soit l'anglais. 
Je propose de retirer les traductions pour simplifier l'utilisation du composant dans ces différents contexes.
BC visuel, la traduction n'est plus affichée dans les options de la liste déroulante.
https://jira.dti.ulaval.ca/browse/ENA2-10918
> [m-phonefield] Retirer les traductions de pays de la liste déroulante

- packages/modul-components/src/components/postalcodefield/postalcodefield.ts
- src/storybook/src/modul-components/components/postalcodefield/postalcodefield.stories.ts
Ajouter la possibilité de mettre 5 ou 9 chiffres séparés par un trait d'union
https://jira.dti.ulaval.ca/browse/ENA2-10403
> [m-postalcodefield] - Modifier le zip code USA

- packages/modul-components/src/components/phonefield/phonefield.html
- packages/modul-components/src/components/phonefield/phonefield.ts
- packages/modul-components/src/components/select/base-select/base-select.html
- packages/modul-components/src/components/select/base-select/base-select.ts
- packages/modul-components/src/components/select/select.html
- packages/modul-components/src/components/select/select.ts
- src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
- src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
- src/storybook/src/modul-components/components/select/select.stories.ts
- Correction du focus après avoir vidé le champs
- Correction de l'utilisation des 2 niveaux de scoped slot
- Correction du émit (selected-item)
[ENA2-10114](https://jira.dti.ulaval.ca/browse/ENA2-10114)
> [m-select] Corrections focus, slots et emit

- packages/modul-components/package.json
Les svg dans les sous dossier netait pas copier dans /dist
> [m-rich-text-editor] copy svg to dist

- packages/modul-components/src/components/accordion/accordion.spec.ts
- packages/modul-components/src/components/checkbox/checkbox.html
- packages/modul-components/src/components/checkbox/checkbox.scss
- packages/modul-components/src/components/checkbox/checkbox.ts
- packages/modul-components/src/components/phonefield/phonefield.html
- packages/modul-components/src/mixins/input-width/input-width.ts
- src/storybook/src/modul-components/components/checkbox/__snapshots__/checkbox.stories.ts.snap
- src/storybook/src/modul-components/components/checkbox/checkbox.stories.ts
- src/storybook/src/modul-components/components/datepicker/__snapshots__/datepicker.stories.ts.snap
- src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
- src/storybook/src/modul-components/components/form/__snapshots__/form.rules.stories.ts.snap
- src/storybook/src/modul-components/components/input-group/__snapshots__/input-group.stories.ts.snap
- src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
Amélioration de l'accessibilité du composant m-checkbox en ajoutant un texte caché dans la balise label lorsque nous ne voulons pas afficher visuellement la label du composant.
**Modification dans le m-checkbox**
- La prop `ariaLabel: string` a été ajouté
- La variable id a été converti en prop
- Nettoyage du code ts composant (supression de code nom utilisé dans le template et remplacer méthodes private par public)
**Comment tester**
- Lien vers la story: http://localhost:8082/?path=/story/modul-components-m-checkbox--hidden-label
- Inspecter l'élément du composant et regarder si le texte de la prop est bien ajouté dans le HTML.
Lien vers la story: http://localhost:8082/?path=/story/modul-components-m-checkbox--hidden-label
> m-checkbox: ajouter la prop "hiddenLabel: string"

- packages/modul-components/src/utils/dialog/dialog-service.ts
- src/storybook/src/modul-components/components/dialog/sandboxes/dialog-service.sandbox.html
- src/storybook/src/modul-components/components/dialog/sandboxes/dialog-service.sandbox.ts
Il faut que la promesse soit résolue sur le clique du bouton secondaire
[ENA2-11175](https://jira.dti.ulaval.ca/browse/ENA2-11175)
> [m-dialog-service] Résoudre la promesse sur le clique du bouton secondaire

- packages/modul-components/src/utils/toast/toast-service.ts
- src/storybook/src/modul-components/components/toast/__snapshots__/toast.stories.ts.snap
- src/storybook/src/modul-components/components/toast/toast.stories.ts
Accepter le HTML dans le toast-service
http://localhost:8082/?path=/story/modul-components-m-toast-toast-service--text-with-html
http://localhost:8082/?path=/story/modul-components-m-toast-toast-service--text-with-html
> [toast-service] Accepter le HTML dans le toast-service

- packages/modul-components/src/components/form/control-directive.ts
Pour enlever l'erreur que l'élément n'est pas déféni, j'ajoute une condition qui vérifie que l'élément existe.
> [m-control-directive] Ajouter une condition sur le bind et unbind

- packages/modul-components/src/components/limit-elements/limit-elements.html
- src/storybook/src/modul-components/components/limit-elements/__snapshots__/limit-elements.stories.ts.snap
- src/storybook/src/modul-components/components/limit-elements/limit-elements.stories.ts
> [m-limit-elements] - Ajout des slots

- src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.html
- src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.ts
Ajout d'une story avec éditeur de texte riche dans le form group complexe
> [m-form] Ajout d'une story avec un éditeur de texte riche

- packages/modul-components/package.json
- yarn.lock
- Les testes ont été  dans BRIO par Sylvie Beaudoin.
-  Resultat des testes de Sylvie( voir wiki https://wiki.dti.ulaval.ca/display/ENA2/Tests+version+3.1.1+de+Froala);
- Le mis à jour a été autorisé par Annie dans le billet https://jira.dti.ulaval.ca/browse/ENA2-10269 .
> ENA2-10269 - MAJ froala version 3.1.1

- packages/modul-components/src/components/searchfield/searchfield.html
- packages/modul-components/src/components/searchfield/searchfield.scss
- src/storybook/src/modul-components/components/searchfield/__snapshots__/searchfield.stories.ts.snap
Correction de l'alignement de l'icône de la loupe qui n'était plus centré verticalement.
> MSearchfield - Alignement de l'icône de recherche

- packages/modul-components/src/components/photo-editor/photo-editor.lang.en.json
- packages/modul-components/src/components/photo-editor/photo-editor.lang.fr.json
https://jira.dti.ulaval.ca/browse/ENA2-11333
> Modification du titre du photo editor

- packages/modul-components/src/components/repeater/repeater.ts
- src/storybook/src/modul-components/components/repeater/__snapshots__/repeater.stories.ts.snap
> [m-repeater] Fix pour problem dans 1_2

- packages/modul-components/src/components/dropdown/dropdown.ts
> [m-dropdown ]add filter to dropdown

- packages/modul-components/src/components/toast/toast.scss
- packages/modul-components/src/utils/toast/toast-service.ts
Permet de rendre compatible le service de toast avec le build runtime de vue qui lui est compatible avec les CSP (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)
> [m-toast] Rendre compliant le toast service avec le build runtime de vue

- packages/modul-components/src/components/dialog/dialog.html
- packages/modul-components/src/components/dialog/dialog.ts
- src/storybook/src/modul-components/components/dialog/__snapshots__/dialog.stories.ts.snap
- src/storybook/src/modul-components/components/dialog/dialog.stories.ts
Ajout de la props okBtnSkin pour avoir plus de flexibilité avec le service de dialog
- [x ] Amélioration (ajout par example une nouvelle propriété, évènement, slot ou méthode à un composant existant sans `breaking change`)
[https://jira.dti.ulaval.ca/browse/ENA2-12462](https://jira.dti.ulaval.ca/browse/ENA2-12462)
> [m-dialog] Ajout props okButtonSkin

- packages/modul-components/src/components/responsive-table/responsive-table.ts
- packages/modul-components/src/components/responsive-table/table-group/table-group.scss
- packages/modul-components/src/components/responsive-table/table-head/table-head.html
- packages/modul-components/src/components/responsive-table/table-head/table-head.ts
- src/storybook/src/modul-components/components/responsive-table/responsive-table.stories.ts
Lorsque nous utilisons la prop `columns `du `m-responsive-table`, il nous arrive parfois de changer dynamiquement la valeur de la prop. Le problème est le suivant: lorsqu'on modifie la valeur de la prop `columns`, les données ne se mettent pas à jour dans le tableau.
> [m-responsive-table] Ameliorer reactivite prop columns

- packages/modul-components/src/components/responsive-table/responsive-table-commons.ts
- packages/modul-components/src/components/responsive-table/responsive-table.html
- packages/modul-components/src/components/responsive-table/responsive-table.scss
- packages/modul-components/src/components/responsive-table/responsive-table.ts
- packages/modul-components/src/components/responsive-table/table-empty-row/table-empty-row.html
- packages/modul-components/src/components/responsive-table/table-group/table-group.scss
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table-custom-class-name.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table-custom-html.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-empty-row.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-groupe-header-style.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-head-style.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-rows-style.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/group-header-custom-class-name.css
- src/storybook/src/modul-components/components/responsive-table/responsive-table.stories.ts
- src/storybook/src/modul-components/components/responsive-table/table-head-style.stories.ts
Permettre de personnaliser l'espacement entre deux rows-group.
Deux propriété ont été ajouté au MTableRowsGroup:
```
{
spacingTop?: string;
spacingClassName?: string;
}
```
Voir la nouvelle story : http://localhost:8082/?path=/story/modul-components-m-responsive-table--row-groups-spacing-top 
http://localhost:8082/?path=/story/modul-components-m-responsive-table--row-groups-spacing-top
> m-responsive-table: Personnalisation du spacingTop sur les rows-group

- packages/modul-components/src/components/photo-editor/photo-editor.html
- packages/modul-components/src/components/photo-editor/photo-editor.ts
ajout d'une nouvelle propriété titleModal que permettre passer le titre du modal dynamique
> [m-photo-editor] - Ajout de prop titre modal

- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.ts
- packages/modul-components/src/components/navbar/navbar-item/navbar-item.html
- packages/modul-components/src/components/navbar/navbar-item/navbar-item.scss
- packages/modul-components/src/components/navbar/navbar-item/navbar-item.spec.ts
- packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
- packages/modul-components/src/components/navbar/navbar.html
- packages/modul-components/src/components/navbar/navbar.scss
- packages/modul-components/src/components/navbar/navbar.ts
- src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
- src/storybook/src/modul-components/components/navbar/navbar.stories.ts
- src/storybook/src/modul-components/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
- Utilisation du composant `m-auto-horizontal-scroll` dans le `m-navbar`
- Ajout d'une animation lors du défilement de gauche à droite
- Ajout du drag pour faire défiler le contenu du navbar de gauche à droite
- Retirer les **promesse** et le `setTimeout()` inutiles dans le  `m-navbar`
- Supression des styles qui ne sont plus utilisés suite à l'importation du `m-auto-horizontal-scroll` dans le `m-navbar`
- Bonification des roles-aria pour l'accessibilité dans le `m-navbar` et `m-navbar-item`
- Correction du bogue de boucle infini avec le `setInterval()` dans le `m-auto-horizontal-scroll`
https://jira.dti.ulaval.ca/browse/MODUL-753
> [m-navbar]  Refactoring du composant pour améliorer l'animation, l'usabilité et l'accessibilité

- packages/modul-components/src/styles/base/_base.scss
- packages/modul-components/src/styles/mixins/_typography.scss
J'ai ajouté des custom properties (variables css) pour les quelques styles de base qui leakaient dans les css non scoper de brio
Le problème est causé par la classe .m-u--app-body qui augmente la spécificité de ces styles et qui nous obligeait à surenchérir inutilement de notre côté.
Il ne devrait pas y avoir aucun changement, les valeurs de base étant les mêmes. Les var css nous permettent simplement de redéfinir plus facilement les valeurs de notre côté.
P.s. Perso je pense que ces styles ne devraient même pas être dans modUL, mais bon pour respecter les besoins des projets moins récents je propose un compromis. ;)
https://jira.dti.ulaval.ca/browse/ENA2-12436
> [scss] -  Ajout des vartiable css pour les styles globaux (.m-u--app-body)

- packages/modul-components/src/components/navbar/navbar.ts
- src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
Corriger le bogue dans Brio concernant la présence d'un $el undefined dans le navbar.
La problème de couleur du bouton précédent et suivant sera réglé dans une autre PR.
> [m-Navbar] $el undefined dans le navbar

- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll-unscoped.scss
- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.html
- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.scss
- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.ts
- packages/modul-components/src/components/navbar/navbar-item/navbar-item.scss
- packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
- packages/modul-components/src/components/navbar/navbar-unscoped.scss
- packages/modul-components/src/components/navbar/navbar.scss
- packages/modul-components/src/components/navbar/navbar.ts
- src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
- src/storybook/src/modul-components/components/navbar/navbar.stories.ts
Ajout de variables CSS dans le navbar pour simplifier la modification du visuel du `m-navbar` et du `m-navnar-item`.
> [m-navbar] Permettre de personnalisé les styles du navbar avec des variables CSS

- packages/modul-components/src/utils/clean/htmlClean.ts
- src/storybook/src/modul-components/components/empty-area/__snapshots__/empty-area.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-conflict/__snapshots__/error-conflict.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-resource-unavailable/__snapshots__/error-resource-unavailable.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table.stories.ts.snap
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-empty-row.stories.ts.snap
- src/storybook/src/modul-components/components/svg/__snapshots__/svg-categories.stories.ts.snap
- src/storybook/src/modul-components/components/svg/__snapshots__/svg.stories.ts.snap
Pour une raison inconnue, le composant svg passe un objet vide et non une string lors de l<appel a htmlClean, cela provoque plusieurs erreur de type (html.replace is not a fonction) lors des l'execution des tests de snapshot
> [m-svg ] Correction erreur "replace is not a function" lors des tests de snapshot

- packages/modul-components/src/components/popper/popper.html
- packages/modul-components/src/components/popper/popper.ts
- packages/modul-components/src/components/popup/popup.html
- packages/modul-components/src/components/popup/popup.ts
- packages/modul-components/src/components/select/base-select/base-select.html
- packages/modul-components/src/components/select/base-select/base-select.ts
- packages/modul-components/src/components/sidebar/sidebar.html
- packages/modul-components/src/components/sidebar/sidebar.ts
- packages/modul-components/src/components/toast/toast.spec.ts
- packages/modul-components/src/components/tooltip/tooltip.scss
- packages/modul-components/src/components/typeahead/typeahead.html
- packages/modul-components/src/mixins/portal/portal.ts
- src/storybook/src/modul-components/components/address/address-editor/__snapshots__/address-editor.stories.ts.snap
- src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
- src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
- src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap
- src/storybook/src/modul-components/components/option/__snapshots__/option.stories.ts.snap
- src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
- src/storybook/src/modul-components/components/popper/__snapshots__/popper.stories.ts.snap
- src/storybook/src/modul-components/components/popup/__snapshots__/popup.stories.ts.snap
- src/storybook/src/modul-components/components/popup/popup.stories.ts
- src/storybook/src/modul-components/components/select-virtual-scroll/__snapshots__/select-virtual-scroll.stories.ts.snap
- src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
- src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
- src/storybook/src/modul-components/components/timepicker/__snapshots__/timepicker.stories.ts.snap
- src/storybook/src/modul-components/components/tooltip/__snapshots__/tooltip.stories.ts.snap
- src/storybook/src/modul-components/components/typeahead/__snapshots__/typeahead.stories.ts.snap
L'objectif de cette PR est d'améliorer la réactivité de la prop open et des slots (header, default et footer) des composants qui utilisent le `m-popup`.
Reformatage du code selon les normes actuelles dans les composants suivants:
* `m-popper`
* `m-sidebar`
* `m-pupup`
* `m-base-select`
* `portal.ts` (mixin)
Dans le composant `m-popup`, la balise racine `div` a été retiré. Les composants `m-popper` en desktop et `m-sidebar` en mobile sont maintenant positionnés à la racine du composant. Cette modification fait en sorte que tous les snapshots des composants qui utilisent un `m-popup` sont réécrits.
@vidal7 
Avant de merger cette PR, un développeur du projet Brio devrait tester cette branche dans leur projet pour s'assurer qu'aucune régression ne sera intégrée à Modul. Voici ce qui devra …
> [m-popup] [m-select] Problème d'affichage lorsqu'on passe de mobile à desktop

- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.html
- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.scss
Changer visuel du cursor au drag du m-auto-horizontal-scroll
> m-auto-horizontal-scroll: Changer visuel du cursor au drag du m-auto-horizontal-scroll

- packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.ts
- packages/modul-components/src/utils/address-lookup/address-lookup.plugin.ts
- src/storybook/src/modul-components/components/address/address-autocomplete-field/__snapshots__/address-autocomplete-field.stories.ts.snap
- src/storybook/src/modul-components/components/address/address-lookup-field/address-lookup-field.stories.ts
1. Enlever les erreurs dans la console dans storybooke et lros des tests de snapshot du m-address lorsque le service loquate n'est pas defini
2. L'erreur You need to install a loquate service dans le m0address plugin est changé pour une Warn
> [m-address] Enlever erreur dans la console dans storybook

- src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
- src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts
> [storybook] Fin de div manquante dans les storybooks du m-drodown

- src/storybook/conf/storybook/config.jest.ts
- src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table.stories.ts.snap
- src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
- src/storybook/tests/polyfills.js
Ajout d'une condition pour enlever les warning vue lors d<un yarn run test et enlever un polyfill qui causait des erreurs dans la console
Sans savoir pourquoi il y a des snapshot de changer pour le m-table ?
> [storybook ]reduction erreurs dans la console lors de execution des tests

- packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.ts
**Problème**
Dans le menu (m-navbar) administrateur de Brio, lorsqu'on navigue d'un item à l'autre et qu'un zoom du navigateur est appliqué, le menu tombe dans une boucle infinie. 
https://develop-www.dev.brioeducation.ca/administration/
**Solution**
Empêcher une boucle infinie lorsque le scrollLeftOffset minimum ou maximum est atteint
> [m-auto-horizontal-scroll] Empêcher une boucle infinie lorsque le scrollLeftOffset minimum ou maximum est atteint

- packages/modul-components/src/assets/icons/svg/compare.svg
- packages/modul-components/src/utils/modul-icons/modul-icons.ts
- src/storybook/src/modul-components/components/svg/__snapshots__/svg-categories.stories.ts.snap
- src/storybook/src/modul-components/components/svg/svg-importation.ts
Ajout du SVG `compare.svg` dans les `assets/icon/svg` et dans `modul-icons.ts`.
Voir l'icône compare: http://localhost:8082/?path=/story/modul-components-m-svg-categories--control
> [MODUL-ICONS] Ajouter un nouveau SVG: compare.svg

- packages/modul-components/src/utils/props-validation/props-validation.ts
Ajouter les unités vw et vh REGEX_CSS_NUMBER_VALUE
> [misc] - Ajouter unité vw et vh à la REGEX_CSS_NUMBER_VALUE

- packages/modul-components/src/filters/date/date-time/date-time.ts
- packages/modul-components/src/filters/date/period/period.spec.ts
- packages/modul-components/src/filters/date/period/period.ts
Prise en charge du 3e paramètre "withParameter" de PeriodFilter.formatPeriod pour afficher les heures et les minutes dans tous les cas (même journée, mais aussi même mois, même année ou année différente).
[ENA2-12968](https://jira.dti.ulaval.ca/browse/ENA2-12968)
> [f-m-date-time  f-m-period ] - Toujours prendre en compte param withTime

- packages/modul-components/src/components/accordion/accordion.html
- packages/modul-components/src/components/accordion/accordion.ts
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
- src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
Renommer variable et methode:
* `internalPropOpen `-> `internalOpen`
* `clickEvent `-> `emitClick`
Utiliser des getter dans le .ts pour les conditions complexes du HTML
* isIconPositionLeft
* isIconSizeLarge
* headerHiddenText
Ajouter `Enums.toValueArray()` dans les validateur de prop
* skin
* iconPosition
* iconSize
Afficher le `headerHiddenText` seulement lorsque l'accordéon n'est pas disabled et que la default slot est défini.
Uniformiser la structure du code selon les normes d'aujourd'hui.
> [m accordion] Reformater le code selon standard (PR1)

- packages/modul-components/src/components/accordion-group/accordion-group.html
- packages/modul-components/src/components/accordion-group/accordion-group.ts
- packages/modul-components/src/components/accordion/accordion.ts
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
Renommer variable et methode:
* applyValuePropChange -> onOpenedIdsChange
Uniformiser la structure du code selon les normes d'aujourd'hui.
* Changer l'ordre des attribut sur les balise HTML
* Changer l'ordre des methodes et des variables private/public/protected/emit/watch/etc.
* Remplacer le composant <m-i18n> par l'utilisation du $i18n.translate() dans le template 
* Remplacer la balise div d'entete par la balise header.
* Améliorer la réactivité des slots en remplacent les getter/computed qui utilisaient les slots par des methodes standards.
Ce PR ne comporte acun breaking change. Des éléments dans le HTML ont été modifiés ce qui modifie le HTML des stories.
> [m accordion-group] Reformater le code selon standard et amélioration sémantique html

- packages/modul-components/src/components/accordion/accordion.html
- packages/modul-components/src/components/accordion/accordion.lang.en.json
- packages/modul-components/src/components/accordion/accordion.lang.fr.json
- packages/modul-components/src/components/accordion/accordion.ts
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
- src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
- src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
- src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
Reverts ulaval/modul#431
Mauvaise branche de destionation
> Revert "[m-accordeon] Ajuster accessibilité du m-accordeon (PR2)"

- packages/modul-components/src/components/breadcrumbs/breadcrumbs.html
- packages/modul-components/src/components/breadcrumbs/breadcrumbs.ts
> [m-breadcrumbs] mauvaise déclaration des sous composant

- packages/modul-components/src/components/datepicker/datepicker.ts
- packages/modul-components/src/components/timepicker/timepicker.ts
- src/storybook/src/modul-components/components/datepicker/__snapshots__/datepicker.stories.ts.snap
- src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
- src/storybook/src/modul-components/components/form/__snapshots__/form.validators.stories.ts.snap
> [m-datepicker] [m-timepicker] probleme init datepicker timepicker

- packages/modul-components/src/components/limit-text/limit-text.ts
- packages/modul-components/src/components/photo-editor/photo-editor.ts
> add missing local component

- packages/modul-components/package.json
- yarn.lock
Mise à jour de libphonenumber-js pour supporter les nouveaux numéros de téléphone à 10 chiffres de la Côte d'Ivoire.
> Update libphonenumber-js pour Cote Ivoire
