ulaval/modul

packages/modul-components/src/mixins/portal/portal.ts
Lorsque le setFocusToPortal ne trouve pas le portal dans le Dom, on n'essaie pas d'y ajouter des attributs
Lancer un overlay en appelant une méthode async qui prend plus de temps à se terminer que la valeur de transitionDuration. Le focus se fait appeler avant la création de la fenêtre
=> N'essaie plus de mettre le focus quand l'élément n'est pas là

packages/modul-components/src/components/link/link.scss
Modification pour afficher un curseur de type pointer sur un lien mlink lorsqu'il n'est pas disabled.
=> use cursor pointer by default on mlink

packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html, packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts, packages/modul-components/src/components/rich-text-editor/rich-text-editor.html
Le but est de résoudre le problème de focus entre l'éditeur rte et la fenêtre d'insertion de lien de froala. En effet, l'éditeur prend le focus lorsque l'on clique sur un champ de la fenêtre d'insertion de lien. Pour résoudre cela, l'évènement click n'est propagé que si aucune popup n'est ouverte.
=> resolve rte focus problem

packages/modul-components/src/components/address/address.ts, packages/modul-components/src/utils/address-lookup/address-lookup-proxy-google-service.ts, packages/modul-components/src/utils/address-lookup/address-lookup-proxy-google.ts, packages/modul-components/src/utils/address-lookup/address-lookup-response-mapper.ts, packages/modul-components/src/utils/address-lookup/address-lookup.plugin.ts
Le proxy google pour le composant adresse prends une promise plutôt qu'un URL, ainsi il est possible d'ajouter des headers custom dans sa requête (notamment l'authentification).
Dans ma branche Brio ENA2-8168
Address Lookup Google Proxy service needs a Promise instead of a URL..
https://jira.dti.ulaval.ca/browse/MODUL-1204
https://jira.dti.ulaval.ca/browse/ENA2-8168
=> MODUL-1204 - Use Promise instead of url on proxy google

packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
Retirer l'attribut srcset lors du remplacement d'une image dans le RTE.
https://jira.dti.ulaval.ca/browse/ENA2-8551
=> ENA2-8551 - ajout retrait srcset sur les images dans froala

packages/modul-components/src/components/dropdown/dropdown.ts, src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap, src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts, src/storybook/src/modul-components/components/overlay/overlay.stories.ts
Disable dropdown input focus after item selection on Android, we still have the internalIsFocus for the dropdown.
=> bugfix/m-dropdown-focus-mobile => disable dropdown input focus

packages/modul-components/src/components/inplace-edit/inplace-edit.html
Dans le inplace-edit il y a maintenant un "velop" en trop qui apparaît.  Je pense que c'est p-e une erreur de merge.
https://jira.dti.ulaval.ca/browse/ENA2-9032
=> [m-inplace-edit] Enlever velop en trop

packages/modul-components/src/filters/date/time/time.ts
Il y a une erreur de formatage d'heure dans les browsers modernes.  Il ne devrait pas y avoir de traling 0s quand on  formate une heure en fr_CA.
https://bugs.chromium.org/p/chromium/issues/detail?id=982778#c3
Faudrait probablement ouvrir un bug sur mozilla aussi.
=> [f-m-date] Fixer l'erreur de formatage de l'heure pour fr-CA.

packages/modul-components/src/components/expandable-layout/expandable-layout.html, packages/modul-components/src/components/expandable-layout/expandable-layout.scss, packages/modul-components/src/components/expandable-layout/expandable-layout.ts, src/storybook/src/modul-components/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap, src/storybook/src/modul-components/components/expandable-layout/expandable-layout.stories.ts
Ajout d'une prop overContent pour que le panel passe par dessus le contenu
[https://jira.dti.ulaval.ca/browse/ENA2-8583](https://jira.dti.ulaval.ca/browse/ENA2-8583)
=> [m-expendable-layout] Ajout prop overContent dans le m-expendable-layout

.gitignore, packages/modul-components/src/utils/http/http.ts
#116  Description
Modification to utility class HttpService to take the timeout parameter from the RequestConfig passed by parameters.
Found a request that took more than 30 seconds to execute to trip the default timeout. Upload a file with 3g speed in chrome. 
Next, I replaced buildConfig method by redefining the prototype with the proposed changes and confirmed that I can pass a different timeout parameter for a particular request (file upload for example). 
https://jira.dti.ulaval.ca/browse/AEL-1999
=> [$http] Feature/ael 1999

packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Deleted imageResizeWithPercent option.
https://jira.dti.ulaval.ca/browse/MODUL-1062
=> [m-rich-text-editor] Keep images size in px after resizing

packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Problème d'overlap du texte d'une deuxième zone de texte riche par dessus les popups du première
=> Retirer le z-index des options par défauts du MRichTextEditor 

packages/modul-components/src/components/phonefield/phonefield.ts, packages/modul-components/src/utils/component/component-mixin.ts, packages/modul-components/src/utils/svg/sprites.ts
Ajout d'une méthode get remove internal sprite au service $svg qui permet d'enlever le sprite du DOM lorsqu'on utilise des sprites locale (comme dans le cas du m-phonefield ou avec l'option sprites du component-mixins)
=> [m-phonefield] cleanup internal sprite

packages/modul-components/src/components/phonefield/phonefield.scss
Fixer la largeur du dropdown du drapeau.
**Problème dans le projet _Dossier individu_**
Il y a espace entre le dropdown de drapeau et le champ de numéro de téléphone.
=> m-phonefield: Fixer la largeur du dropdown du drapeau

packages/modul-components/src/components/table/__snapshots__/table.spec.ts.snap, packages/modul-components/src/components/table/table.html, packages/modul-components/src/components/table/table.scss, src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
**Ajuster la largeur du placeholder du tableau.**
- Ajouter un `colspan="100%"` sur le `<td>` du placeholder du tableau.
- Voir la story : http://localhost:8082/?path=/story/modul-components-m-table--width-placeholer
http://localhost:8082/?path=/story/modul-components-m-table--width-placeholer
=> m-table: ajuster la largeur du placeholder du tableau

packages/modul-components/src/components/popup/popup.html, src/storybook/src/modul-components/components/popup/__snapshots__/popup.stories.ts.snap, src/storybook/src/modul-components/components/popup/popup.stories.ts
closeOnBackdrop seulement sur la sidebar. Sébastien Turcotte en a rajouté un autre sur le popper aussi.
N/A (initiative personnelle sans billet Jira)
=> [m-popup] Impossible de désactiver le du close-on-click-outside sur le popper a partir de la props close on backdrop

packages/modul-components/src/components/spinner/spinner.html, packages/modul-components/src/components/spinner/spinner.scss, packages/modul-components/src/components/spinner/spinner.ts, src/storybook/src/modul-components/components/spinner/__snapshots__/spinner.stories.ts.snap, src/storybook/src/modul-components/components/spinner/spinner.stories.ts
**Problèmes résolus**
- Lorsque la prop `description` est utilisé sans la prop `text`, l'espacement entre l'icône de spinner et la description est insuffisante.
- Lorsque le composant utile la prop `processing: boolean` et que la valeur de cette prop change, le backdrop n'apparait plus en arrière du spinner.
Tester l'utilisation des knobs dans storybook
http://localhost:8082/?path=/story/modul-components-m-spinner-knobs--all-props
=> [m-spinner] Ajuster l'espace entre les texte du spinner et améliorer sa réactivité en mode processing

packages/modul-components/src/components/postalcodefield/postalcodefield.ts, packages/modul-components/src/filters/postal-code/postal-code.ts, src/storybook/src/modul-components/components/postalcodefield/__snapshots__/postalcodefield.stories.ts.snap, src/storybook/src/modul-components/filters/postal-code/__snapshots__/postal-code.stories.ts.snap
Les valeurs de l'enum de postalcodefield auraient dûs être en majuscules pour être consistents avec les autres codes de pays qu'on retrouve dans Modul (comme dans phonefield, par exemple).  
À chaque endroit où le filtre postalCodeFilter est utilisé, il faut changer la casse du paramètre isoCountry afin que la valeur soit en minuscule.
Pour le m-postalcodefield, il faut aussi s'assurer que la casse de la prop soit en minuscule. Dans le cas de Brio, ça ne cause pas de problème parce que c'était les valeurs d'enum qui étaient utilisées. La correction apportée dans Modul n'apporte pas de breaking change.
https://jira.dti.ulaval.ca/browse/ENA2-11208
=> [m-postalcodefield] Changé la casse des codes de pays

packages/modul-components/src/components/accordion/accordion.ts
Désactiver ouverture de l'accordeon sur un élément avec un attribut tabindex
=> [m-accordion] Désactiver ouverture de l'accordeon sur un élément avec un attribut tabindex

packages/modul-components/src/components/multi-select/multi-select.html, packages/modul-components/src/components/multi-select/multi-select.scss, packages/modul-components/src/components/select/base-select/base-select.html, packages/modul-components/src/components/select/base-select/base-select.scss, packages/modul-components/src/components/select/select.html, packages/modul-components/src/components/select/select.scss, packages/modul-components/src/components/typeahead/typeahead.html, packages/modul-components/src/components/typeahead/typeahead.scss, src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap, src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.html, src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.ts, src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap, src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts, src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap, src/storybook/src/modul-components/components/select-virtual-scroll/__snapshots__/select-virtual-scroll.stories.ts.snap, src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap, src/storybook/src/modul-components/components/select/select.stories.ts, src/storybook/src/modul-components/components/typeahead/__snapshots__/typeahead.stories.ts.snap, src/storybook/src/modul-components/components/typeahead/typeahead.stories.ts
Lorsque le m-select a une erreur, le popup s'ouvrait dessous le message d'erreur
=> [m-select] Correction de l'espacement du popup lors d'un message erreur

packages/modul-components/src/components/multi-select/multi-select.ts, src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap, src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
Lorsque la liste d'options du multi-select était vide, elle affichait la pastille : [Tous les choix (0) x]. Comme quand toutes les options de la liste sont sélectionnées. J'ai précisé la règle d'affichage de cette pastille pour qu'elle ne s'affiche pas quand il n'y a aucune option dans une liste.
Correction de bug avec breaking change visuel
La liste déroulante multi-select n'affiche plus la pastille "Tous les choix (0)" lorsqu'il n'y a pas d'options qui lui sont passé
=> MMultiSelect - Correction d'affichage lorsque la liste est vide

packages/modul-components/src/components/navbar/navbar-item/navbar-item.html, packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
Lorsque la balise `m-navbar-item` du composant est une `div`, event `@click.native="function()"` ne fonctionne pas.
=> [bugfix] m-navbar-item : Correct native click error in mpo-ui

packages/modul-components/src/components/select/base-select/base-select.html, packages/modul-components/src/components/select/base-select/base-select.ts, packages/modul-components/src/components/select/select.html, packages/modul-components/src/components/select/select.ts, src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap, src/storybook/src/modul-components/components/select/select.stories.ts
Ajout d'une props list-max-height sur le m-base-select et le m-select pour pouvoir paramétrer la hauteur de la liste ouverte
[ENA2-11471](https://jira.dti.ulaval.ca/browse/ENA2-11471)
=> [m-select] Ajout props max-height sur la liste m-select

packages/modul-components/src/components/empty-area/empty-area.scss, packages/modul-components/src/components/responsive-table/table-group/table-group.scss
1- Lorsque le composant `m-empty-area` à la prop `display-mode="inline"` et aucune icone, il faut appliquer le style `text-align: center;` sur le titre et sous-titre.
2- Retirer l'effet de survol du sur le `m-empty-area` dans un `m-table-empty-row`
=> m-empty-area: Text align with display-mode='inline'

packages/modul-components/src/components/message-page/message-page.ts, packages/modul-components/src/lib.ts
Les composantes m-message et m-message-page partagent le même ENUM pour la définition de l'état (confirmation, info, warn, error). 
Ce partage d'énum peut entrainer un cycle dans les importations. La solution a donc été de définir un énum d'état pour m-message.
La solution optimale serait d'extraire cet énum d'état et que toutes les composantes le réquérant l'importe (centraliserait les sources de changement et éviterait la répétition).
Le seul test possible est d'avoir un projet créant le cycle de d'import
Creation of an ENUM specific for the configuration of the component `m-message-page` (`MMessagePageState`). The current one (`m-message-state`) can still be used but it might create an import cycle while using `m-dialog` + `m-message` + `m-message-page` …
=> Given m-message-page it's own state ENUM

packages/modul-components/src/components/multi-select/multi-select.html, packages/modul-components/src/components/multi-select/multi-select.ts
Uses default formatting for the multiselect component selected items count. This fixes a case where the i18n formatting is different in a consumer project. Since this component uses the {0} parameters format, the translation is broken when using the Sprintf format (%(var)s).
Imported in another project with different formatting.
No Jira ticket.
=> Use default i18n formatting w/multi-select 

packages/modul-components/src/components/responsive-table/responsive-table-commons.ts
Remplacer le type `MEmptyAreaDisplayMode` de `MTableEmptyArea.svgSize` par le type `string`.
=> [m-responsive-table] Modifier le type de MTableEmptyArea.svgSize

packages/modul-components/src/assets/icons/svg/clock.svg, packages/modul-components/src/assets/icons/svg/code-tag.svg, src/storybook/src/modul-components/components/svg/svg-importation.ts
Les traits des deux SVG suivants ont été modifiés: `clock.svg` et `code-tag.svg`.
Le styles des traits de ces deux SVG n'étaient uniformes aux autres SVG de type icône.
La propriété `stroke-linecap="round"` a été ajouter sur les trait pour les arrondir.
Cette modification n'implique aucun breaking change.
Voir les icônes **clock** et **code-tag** dans cette story: 
http://localhost:8082/?path=/story/modul-components-m-svg-categories--default-story
Voir les icônes **clock** et **code-tag** dans cette story: 
http://localhost:8082/?path=/story/modul-components-m-svg-categories--default-story
=> [ICONS/SVG] Uniformiser les traits de deux SVG

packages/modul-components/src/components/multi-select/multi-select.ts, src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap, src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
La prop Options provient parfois d'un appel async a un service. La valeur des options peut alors être temporaire undefined en attendant que les options soient obtenus. Une erreur était alors obtenu. Ce changement permet de supporter options=undefined. Il se comporte comme dans les cas options=[]
=> [m multi-select] Supporter la prop Options à undefined

packages/modul-components/src/components/periodpicker/periodpicker.ts
Dans la class MDateRange, la méthode toIsoString utilise la donnée "from" au lieu de "to".
=> [m-periodpicker] toIsoString utilise la donnée "from" au lieu de "to"
